name: Test
on: 
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image'     
        required: true
        default: 'haxorof/ansible:v2.10'
jobs:
  security-scan-table:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ github.event.inputs.image }}'
          format: 'table'
          exit-code: '1'
          # ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  # security-scan-upload-results:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         image-ref: 'docker.io/${{ github.event.inputs.image }}'
  #         format: 'template'
  #         template: '@/contrib/sarif.tpl'
  #         output: 'trivy-results.sarif'

  #     - name: Upload Trivy scan results to GitHub Security tab
  #       uses: github/codeql-action/upload-sarif@v1
  #       with:
  #         sarif_file: 'trivy-results.sarif'